mkdir -p $1/bin
cp ./Vector/OGR2OGR/CreateCSVfromSHP.py $1/bin/
cp ./Text/FindReplaceTextDIR.py $1/bin/
cp ./Text/JoinTablesCSV.py $1/bin/
cp ./gdalrats/setthematic.py $1/bin/
cp ./File/Rename/reFindandReplaceFileName.py $1/bin/
cp ./GDAL/setbandname.py $1/bin
cp ./GDAL/subsetImage2Image.py $1/bin
cp ./TuiView/export_quicklook_tuiview.py $1/bin
cp ./classification/GenerateClassLegend.py $1/bin
