# ---------------------------------------------------------------------------
# seg from model.py
# Created on: Ôñé Éïõí 19 2007 11:38:16 ðì
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------
import sys
import os
import string
import imghdr
import Image
import win32com.client

gp = win32com.client.Dispatch("esriGeoprocessing.GpDispatch.1")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Segmentation.tbx")


# Local variables...
Sigma = "0.5"
Min = "20"
K = "500"
data = "C:\\data"
new = "C:\\data\\new"

images = "C:\\data\\images"

# Process: Segmentation...
gp.toolbox = "C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Segmentation.tbx"
gp.Segmentation(Sigma, K, Min, Forest_jpg, images, data)


gp.AddMessage('FINISHED!')