 #! /usr/bin/env python

#######################################
# A python script to plot histograms
# generated by RSGISLib
#
# Email: petebunting@mac.com
# Date: 16/07/2012
# Version: 1.0
#######################################

import os.path
import sys
from math import *
import matplotlib.pyplot as plt

def readCSVFile(inFile, binValues, binFreqs):
    line = 0
    inFile.seek(0)
    for eachLine in inFile:
        eachLine = eachLine.strip()
        if eachLine != "":
            split = eachLine.split(',', eachLine.count(','))
            binValues.append(float(split[0]))
            binFreqs.append(float(split[1]))

def plotHistogram(inFile, outPlot, colour, name, classStr):
    binValues = list()
    binFreqs = list()

    try:
        inFileTxt = open(inFile.strip(), 'r')
        readCSVFile(inFileTxt, binValues, binFreqs)
        inFileTxt.close()
    except IOError, e:
        print '\nCould not open file:\n', e
        sys.exit()

    fig = plt.figure(figsize=(12, 12), dpi=80)

    histPlot = plt.bar(binValues, binFreqs, width=5, bottom=0, color=colour, linewidth=0)

    titleStr = str("Histogram for ") + name + str(" LCDB3 Class ") + classStr
    plt.title(titleStr)
    plt.xlabel(name)
    plt.ylabel("Freq.")


    plt.savefig(outPlot, format='PDF')

    #plt.show()


inputFile = sys.argv[4].strip()
outputFile = sys.argv[5].strip()
colourIn = sys.argv[1].strip()
nameIn = sys.argv[2].strip()
classIn = sys.argv[3].strip()

plotHistogram(inputFile, outputFile, colourIn, nameIn, classIn)
